management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, httptrace, busrefresh

spring:
  main:
    allow-bean-definition-overriding: true

  profiles:
    active: local

  cloud:
    config:
      name: bbl-gateway

  config:
    import: optional:configserver:http://127.0.0.1:8888/