management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, httptrace, busrefresh

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  profiles:
    active: local

  cloud:
    config:
      name: bbl-payment

  config:
    import: optional:configserver:http://127.0.0.1:8888/

